export const NAVIGATION = {
  home: 'Home',
  login: 'Login',
  register: 'Register',
  profile: 'Profile',
  editProfile: 'editProfile',
  user: 'user',
  payment: 'payment',
  paymentMethod: 'paymentMethod',
  cardless: 'cardless',
  invoice: 'invoice',
  myAddress: 'myAddress',
  addAddress: 'addAddress',
  invoice: 'invoice',
  // notification: 'notification',
  forgetpassword: 'ForgetPassword',
  verification: 'Verification',
  onboarding: 'Onboarding',
  reset: 'ResetPassword',
  schedule: 'Schedule',
  chat: 'Chat',
  serviceRequest: 'ServiceRequest',
  serviceQuestion: 'ServiceQuestion',
  orderSummary: 'OrderSummary',
  orderDetails: 'OrderDetails',
  chatlist: 'ChatList',
  livetracking: 'LiveTracking',
  notificationList: 'NotificationList',
};
